<a href="https://colab.research.google.com/github/martinsadw/alura/blob/main/Pandas%20-%20selecionando%20e%20agrupando%20dados/conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -O emission.xlsx https://cdn3.gnarususercontent.com.br/2927-pandas-selecao-agrupamento-dados/1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx
!wget -O population.xlsx https://cdn3.gnarususercontent.com.br/2927-pandas-selecao-agrupamento-dados/POP2022_Municipios.xls

--2024-04-24 17:29:20--  https://cdn3.gnarususercontent.com.br/2927-pandas-selecao-agrupamento-dados/POP2022_Municipios.xls
Resolving cdn3.gnarususercontent.com.br (cdn3.gnarususercontent.com.br)... 104.26.14.179, 104.26.15.179, 172.67.75.65, ...
Connecting to cdn3.gnarususercontent.com.br (cdn3.gnarususercontent.com.br)|104.26.14.179|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 757248 (740K) [application/vnd.ms-excel]
Saving to: ‘population.xlsx’

population.xlsx     100%[===================>] 739.50K  --.-KB/s    in 0.04s

2024-04-24 17:29:20 (16.1 MB/s) - ‘population.xlsx’ saved [757248/757248]

In [ ]:
import pandas as pd

# 1. Importing Emission

In [ ]:
excel_emission = pd.ExcelFile('emission.xlsx')
excel_emission.sheet_names

['LEIA ANTES',
 'HISTÓRICO DE VERSOES',
 'GEE Brasil',
 'GEE Estados',
 'CONSULTA BRASIL',
 'CONSULTA ESTADOS',
 'CONSULTA ATIV ECONOMICA',
 'Arvore Hierarquica',
 'GWP e GTP',
 'Gases Por Setor',
 'Estados',
 'Atividade Economica',
 'Produto']

In [ ]:
pd.read_excel(excel_emission, 'GEE Estados', nrows=10)

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,...,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,...,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,...,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,...,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,...,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000
5,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GTP-AR2,SP,OUTRA_IND,...,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000,35100.000000
6,Processos Industriais,Indústria Química,Produção de Ácido Nítrico,NaN,NaN,NaN,Emissão,N2O (t),BA,OUTRA_IND,...,42.408907,41.346807,44.184643,44.184643,44.184643,44.184643,44.184643,44.184643,44.184643,44.184643
7,Processos Industriais,Indústria Química,Produção de Ácido Nítrico,NaN,NaN,NaN,Emissão,NOx (t),BA,OUTRA_IND,...,33.404714,32.568117,34.803429,34.803429,34.803429,34.803429,34.803429,34.803429,34.803429,34.803429
8,Processos Industriais,Indústria Química,Produção de Ácido Nítrico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,BA,OUTRA_IND,...,13146.761156,12817.510091,13697.239462,13697.239462,13697.239462,13697.239462,13697.239462,13697.239462,13697.239462,13697.239462
9,Processos Industriais,Indústria Química,Produção de Ácido Nítrico,NaN,NaN,NaN,Emissão,CO2e (t) GTP-AR2,BA,OUTRA_IND,...,11450.404878,11163.637821,11929.853725,11929.853725,11929.853725,11929.853725,11929.853725,11929.853725,11929.853725,11929.853725

# 2. Importing Population

In [ ]:
excel_population = pd.ExcelFile('population.xlsx')
excel_population.sheet_names

['Municípios']

In [ ]:
data_population = pd.read_excel(excel_population, 'Municípios', skiprows=1, skipfooter=34, dtype={'POPULAÇÃO': str})
data_population['POPULAÇÃO'] = pd.to_numeric(data_population['POPULAÇÃO'].str.replace(r'\(\d+\)', '', regex=True).str.replace('.', ''))
data_population

      UF  COD. UF  COD. MUNIC      NOME DO MUNICÍPIO  POPULAÇÃO
0     RO       11          15  Alta Floresta D'Oeste      21558
1     RO       11          23              Ariquemes     100896
2     RO       11          31                 Cabixi       5107
3     RO       11          49                 Cacoal      92202
4     RO       11          56             Cerejeiras      15237
...   ..      ...         ...                    ...        ...
5565  GO       52       22005             Vianópolis      14046
5566  GO       52       22054         Vicentinópolis       8776
5567  GO       52       22203               Vila Boa       3686
5568  GO       52       22302          Vila Propício       5646
5569  DF       53         108               Brasília    2923369

[5570 rows x 5 columns]

In [ ]:
data_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   UF                 5570 non-null   object
 1   COD. UF            5570 non-null   int64
 2   COD. MUNIC         5570 non-null   int64
 3   NOME DO MUNICÍPIO  5570 non-null   object
 4   POPULAÇÃO          5570 non-null   int64
dtypes: int64(3), object(2)
memory usage: 217.7+ KB

# 3. Exporting

In [ ]:
data_emission = pd.read_excel(excel_emission, 'GEE Estados')
data_emission.to_csv('data_emission.csv', index=False)

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
data_population.to_csv('data_population.csv', index=False)