<a href="https://colab.research.google.com/github/martinsadw/alura/blob/main/Pandas%20IO%20-%20trabalhando%20com%20diferentes%20formatos%20de%20arquivos/Clientes_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv

--2024-04-20 12:13:16--  https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43498463 (41M) [text/plain]
Saving to: ‘clientes_banco.csv’

clientes_banco.csv  100%[===================>]  41.48M  --.-KB/s    in 0.1s

2024-04-20 12:13:16 (325 MB/s) - ‘clientes_banco.csv’ saved [43498463/43498463]

# 1. Importing

In [ ]:
import pandas as pd
import sqlalchemy

In [ ]:
engine = sqlalchemy.create_engine('sqlite:///:memory:')

In [ ]:
clients = pd.read_csv('clientes_banco.csv', index_col='ID_Cliente')
clients

,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
ID_Cliente,,,,,,,,,,
5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...
6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
clients.to_sql('clients', engine)

438463

In [ ]:
inspector = sqlalchemy.inspect(engine)
print(inspector.get_table_names())

['clientes', 'clients']

In [ ]:
query = 'SELECT * FROM clients WHERE Categoria_de_renda = "Empregado"'
employee = pd.read_sql(query, engine, index_col='ID_Cliente')
employee

,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
ID_Cliente,,,,,,,,,,
5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...
6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

# 2. Exporting

In [ ]:
employee.to_sql('employee', engine)

226059

In [ ]:
inspector = sqlalchemy.inspect(engine)
print(inspector.get_table_names())

['clientes', 'clients', 'employee']

In [ ]:
pd.read_sql_table('employee', engine, index_col='ID_Cliente')

,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
ID_Cliente,,,,,,,,,,
5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...
6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
pd.read_sql_table('employee', engine, index_col='ID_Cliente', columns=['Grau_escolaridade', 'Rendimento_anual'])

           Grau_escolaridade  Rendimento_anual
ID_Cliente
5008804      Ensino superior          427500.0
5008805      Ensino superior          427500.0
5008806         Ensino médio          112500.0
5008815      Ensino superior          270000.0
5112956      Ensino superior          270000.0
...                      ...               ...
6837905         Ensino médio          355050.0
6837906         Ensino médio          355050.0
6839936         Ensino médio          135000.0
6840222         Ensino médio          103500.0
6842885         Ensino médio          121500.0

[226059 rows x 2 columns]